Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7"
  c.vm.hostname = "hardened-centos-7.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "C:/Users/zhangc/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-apache-couchdb-srg-baseline-hardened-centos-7-546e1111-472d-4854-9efc-4704f6a841b6"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
