Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/centos-7"
  c.vm.hostname = "couchdb-centos-7.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "C:/Users/zhangc/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-apache-couchdb-srg-baseline-couchdb-centos-7-1cced51d-2bd9-4cd4-8f7a-a22ea2005499"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
